// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// glitch //
// ------ //

#define glitch_wrap_target 0
#define glitch_wrap 9
#define glitch_pio_version 0

static const uint16_t glitch_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa045, //  1: mov    y, status
    0x80a0, //  2: pull   block
    0xa025, //  3: mov    x, status
    0x0084, //  4: jmp    y--, 4
    0xa042, //  5: nop
    0xe001, //  6: set    pins, 1
    0x0047, //  7: jmp    x--, 7
    0xa042, //  8: nop
    0xe000, //  9: set    pins, 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program glitch_program = {
    .instructions = glitch_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = glitch_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config glitch_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + glitch_wrap_target, offset + glitch_wrap);
    return c;
}
#endif

